### ISSUE TITLE
Scope lines not appearing

### ISSUE THREAD

**Issue by stachurr** [dthpham/tree-view-scope-lines#1]
This is not showing the scope lines. When adding this to my 'style.less' file, nothing changes on the tree. I believe either this topic does not fulfill it's purpose in showing how to add the scope lines, or Atom has updated since then and this no longer works. If this is not how you add the scope lines, what is the correct way?

Thank you.

![capture](https://user-images.githubusercontent.com/25037201/31059962-0d59fb6c-a6bf-11e7-8b28-1cffb6bc5a83.JPG)

**Comment by dthpham** [comment]
Remove that snippet from styles.less. Reload the window, then try going into Settings > Packages and then enable and disable the package a few times. What you added to your stylesheet was CSS to customize the color of the scope lines. It won't have an effect if the package isn't activated or if there was a bug of some sort.

**Comment by stachurr** [comment]
Turns out I was running Atom 1.8.x. The update check did not find any new versions so I manually downloaded 1.21.0 and your package worked. Sorry for any inconvenience.
